"""add scan_config and signal_outcomes

Revision ID: 53451fe485b8
Revises: 70ad53a17941
Create Date: 2026-04-30 16:53:26.703927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53451fe485b8'
down_revision: Union[str, Sequence[str], None] = '70ad53a17941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_configs_key'), 'scan_configs', ['key'], unique=True)
    op.create_table('signal_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('tp_price', sa.Float(), nullable=False),
    sa.Column('sl_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=10), nullable=False),
    sa.Column('params_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_outcomes_stock_code'), 'signal_outcomes', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_outcomes_stock_code'), table_name='signal_outcomes')
    op.drop_table('signal_outcomes')
    op.drop_index(op.f('ix_scan_configs_key'), table_name='scan_configs')
    op.drop_table('scan_configs')
    # ### end Alembic commands ###
