"""add stop_loss_price and take_profit_price to auto_trade_configs

Revision ID: 70ad53a17941
Revises: 4c564dbfb203
Create Date: 2026-04-30 16:24:21.388870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ad53a17941'
down_revision: Union[str, Sequence[str], None] = '4c564dbfb203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trade_configs', sa.Column('stop_loss_price', sa.Float(), nullable=True))
    op.add_column('auto_trade_configs', sa.Column('take_profit_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_trade_configs', 'take_profit_price')
    op.drop_column('auto_trade_configs', 'stop_loss_price')
    # ### end Alembic commands ###
